//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.12.1.454
`timescale 1 ns / 1 ps
`include "i2c_pipeline/rom.v"

module rom_tb;
    reg [11:0] Address = 12'b0;
    reg OutClock = 0;
    reg OutClockEn = 0;
    reg Reset = 0;
    wire [23:0] Q;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0;

    rom_i u1 (.Address(Address), .OutClock(OutClock), .OutClockEn(OutClockEn), 
        .Reset(Reset), .Q(Q)
    );

    initial
    begin
       Address <= 0;
      #100;
      @(Reset == 1'b0);
      for (i1 = 0; i1 < 4099; i1 = i1 + 1) begin
        @(posedge OutClock);
        #1  Address <= Address + 1'b1;
      end
      $finish;
    end
    always
    #5.00 OutClock <= ~ OutClock;


    // Dump file declaration
    initial begin
        $dumpfile("out/rom_tb.vcd");
        $dumpvars(0, rom_tb); // Dump all signals
    end

    initial
    begin
       OutClockEn <= 1'b0;
      #100;
      @(Reset == 1'b0);
       OutClockEn <= 1'b1;
    end
    initial
    begin
       Reset <= 1'b0;
      #100;
       Reset <= 1'b1;
    end
endmodule