/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sat Nov 06 18:53:28 2021 */

/* parameterized module instance */
pll1_ip __ (.CLKI( ), .CLKOP( ), .LOCK( ));
