/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Sep 19 01:55:28 2024 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
