/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Oct 24 11:30:01 2024 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
