/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 7.5 */
/* Tue Sep 10 11:29:09 2024 */

/* parameterized module instance */
ram_dq_s __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
