/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* Tue Jul 13 10:52:23 2021 */

/* parameterized module instance */
ping_pong_buffer __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .WCNT( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
