/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Thu Jul 08 20:00:15 2021 */

/* parameterized module instance */
vga_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
