/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 6.5 */
/* Mon Oct 21 18:24:55 2024 */

/* parameterized module instance */
dp_ram __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), .RdClock( ), 
    .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
