/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Sep 05 13:36:20 2024 */

/* parameterized module instance */
pll_ip __ (.CLKI( ), .CLKOP( ), .CLKOS2( ), .LOCK( ));
