/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Fri Oct 25 20:04:01 2024 */

/* parameterized module instance */
pll_i __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
