/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.8 */
/* Tue Jul 13 10:52:52 2021 */

/* parameterized module instance */
intermediate_dc_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), 
    .Empty( ), .Full( ));
